//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDostavaClient.eDostavaServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restoran", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Restoran : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDostavaClient.eDostavaServis.Blok BlokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public eDostavaClient.eDostavaServis.Blok Blok {
            get {
                return this.BlokField;
            }
            set {
                if ((object.ReferenceEquals(this.BlokField, value) != true)) {
                    this.BlokField = value;
                    this.RaisePropertyChanged("Blok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Blok", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Blok : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eDostavaServis.eDostavaServisSoap")]
    public interface eDostavaServisSoap {
        
        // CODEGEN: Generating message contract since element name GetRestoraniByBlokResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestoraniByBlok", ReplyAction="*")]
        eDostavaClient.eDostavaServis.GetRestoraniByBlokResponse GetRestoraniByBlok(eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestoraniByBlok", ReplyAction="*")]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoraniByBlokResponse> GetRestoraniByBlokAsync(eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest request);
        
        // CODEGEN: Generating message contract since element name naziv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestoranByNaziv", ReplyAction="*")]
        eDostavaClient.eDostavaServis.GetRestoranByNazivResponse GetRestoranByNaziv(eDostavaClient.eDostavaServis.GetRestoranByNazivRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestoranByNaziv", ReplyAction="*")]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoranByNazivResponse> GetRestoranByNazivAsync(eDostavaClient.eDostavaServis.GetRestoranByNazivRequest request);
        
        // CODEGEN: Generating message contract since element name GetRestoraniResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestorani", ReplyAction="*")]
        eDostavaClient.eDostavaServis.GetRestoraniResponse GetRestorani(eDostavaClient.eDostavaServis.GetRestoraniRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestorani", ReplyAction="*")]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoraniResponse> GetRestoraniAsync(eDostavaClient.eDostavaServis.GetRestoraniRequest request);
        
        // CODEGEN: Generating message contract since element name GetBlokoviResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlokovi", ReplyAction="*")]
        eDostavaClient.eDostavaServis.GetBlokoviResponse GetBlokovi(eDostavaClient.eDostavaServis.GetBlokoviRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlokovi", ReplyAction="*")]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetBlokoviResponse> GetBlokoviAsync(eDostavaClient.eDostavaServis.GetBlokoviRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestoraniByBlokRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestoraniByBlok", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetRestoraniByBlokRequestBody Body;
        
        public GetRestoraniByBlokRequest() {
        }
        
        public GetRestoraniByBlokRequest(eDostavaClient.eDostavaServis.GetRestoraniByBlokRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestoraniByBlokRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int blokId;
        
        public GetRestoraniByBlokRequestBody() {
        }
        
        public GetRestoraniByBlokRequestBody(int blokId) {
            this.blokId = blokId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestoraniByBlokResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestoraniByBlokResponse", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetRestoraniByBlokResponseBody Body;
        
        public GetRestoraniByBlokResponse() {
        }
        
        public GetRestoraniByBlokResponse(eDostavaClient.eDostavaServis.GetRestoraniByBlokResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestoraniByBlokResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eDostavaClient.eDostavaServis.Restoran[] GetRestoraniByBlokResult;
        
        public GetRestoraniByBlokResponseBody() {
        }
        
        public GetRestoraniByBlokResponseBody(eDostavaClient.eDostavaServis.Restoran[] GetRestoraniByBlokResult) {
            this.GetRestoraniByBlokResult = GetRestoraniByBlokResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestoranByNazivRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestoranByNaziv", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetRestoranByNazivRequestBody Body;
        
        public GetRestoranByNazivRequest() {
        }
        
        public GetRestoranByNazivRequest(eDostavaClient.eDostavaServis.GetRestoranByNazivRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestoranByNazivRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string naziv;
        
        public GetRestoranByNazivRequestBody() {
        }
        
        public GetRestoranByNazivRequestBody(string naziv) {
            this.naziv = naziv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestoranByNazivResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestoranByNazivResponse", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetRestoranByNazivResponseBody Body;
        
        public GetRestoranByNazivResponse() {
        }
        
        public GetRestoranByNazivResponse(eDostavaClient.eDostavaServis.GetRestoranByNazivResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestoranByNazivResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eDostavaClient.eDostavaServis.Restoran[] GetRestoranByNazivResult;
        
        public GetRestoranByNazivResponseBody() {
        }
        
        public GetRestoranByNazivResponseBody(eDostavaClient.eDostavaServis.Restoran[] GetRestoranByNazivResult) {
            this.GetRestoranByNazivResult = GetRestoranByNazivResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestoraniRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestorani", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetRestoraniRequestBody Body;
        
        public GetRestoraniRequest() {
        }
        
        public GetRestoraniRequest(eDostavaClient.eDostavaServis.GetRestoraniRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRestoraniRequestBody {
        
        public GetRestoraniRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestoraniResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestoraniResponse", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetRestoraniResponseBody Body;
        
        public GetRestoraniResponse() {
        }
        
        public GetRestoraniResponse(eDostavaClient.eDostavaServis.GetRestoraniResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestoraniResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eDostavaClient.eDostavaServis.Restoran[] GetRestoraniResult;
        
        public GetRestoraniResponseBody() {
        }
        
        public GetRestoraniResponseBody(eDostavaClient.eDostavaServis.Restoran[] GetRestoraniResult) {
            this.GetRestoraniResult = GetRestoraniResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlokoviRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlokovi", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetBlokoviRequestBody Body;
        
        public GetBlokoviRequest() {
        }
        
        public GetBlokoviRequest(eDostavaClient.eDostavaServis.GetBlokoviRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBlokoviRequestBody {
        
        public GetBlokoviRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlokoviResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlokoviResponse", Namespace="http://tempuri.org/", Order=0)]
        public eDostavaClient.eDostavaServis.GetBlokoviResponseBody Body;
        
        public GetBlokoviResponse() {
        }
        
        public GetBlokoviResponse(eDostavaClient.eDostavaServis.GetBlokoviResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBlokoviResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eDostavaClient.eDostavaServis.Blok[] GetBlokoviResult;
        
        public GetBlokoviResponseBody() {
        }
        
        public GetBlokoviResponseBody(eDostavaClient.eDostavaServis.Blok[] GetBlokoviResult) {
            this.GetBlokoviResult = GetBlokoviResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eDostavaServisSoapChannel : eDostavaClient.eDostavaServis.eDostavaServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eDostavaServisSoapClient : System.ServiceModel.ClientBase<eDostavaClient.eDostavaServis.eDostavaServisSoap>, eDostavaClient.eDostavaServis.eDostavaServisSoap {
        
        public eDostavaServisSoapClient() {
        }
        
        public eDostavaServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eDostavaServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eDostavaServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eDostavaServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eDostavaClient.eDostavaServis.GetRestoraniByBlokResponse eDostavaClient.eDostavaServis.eDostavaServisSoap.GetRestoraniByBlok(eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest request) {
            return base.Channel.GetRestoraniByBlok(request);
        }
        
        public eDostavaClient.eDostavaServis.Restoran[] GetRestoraniByBlok(int blokId) {
            eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest inValue = new eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetRestoraniByBlokRequestBody();
            inValue.Body.blokId = blokId;
            eDostavaClient.eDostavaServis.GetRestoraniByBlokResponse retVal = ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetRestoraniByBlok(inValue);
            return retVal.Body.GetRestoraniByBlokResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoraniByBlokResponse> eDostavaClient.eDostavaServis.eDostavaServisSoap.GetRestoraniByBlokAsync(eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest request) {
            return base.Channel.GetRestoraniByBlokAsync(request);
        }
        
        public System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoraniByBlokResponse> GetRestoraniByBlokAsync(int blokId) {
            eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest inValue = new eDostavaClient.eDostavaServis.GetRestoraniByBlokRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetRestoraniByBlokRequestBody();
            inValue.Body.blokId = blokId;
            return ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetRestoraniByBlokAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eDostavaClient.eDostavaServis.GetRestoranByNazivResponse eDostavaClient.eDostavaServis.eDostavaServisSoap.GetRestoranByNaziv(eDostavaClient.eDostavaServis.GetRestoranByNazivRequest request) {
            return base.Channel.GetRestoranByNaziv(request);
        }
        
        public eDostavaClient.eDostavaServis.Restoran[] GetRestoranByNaziv(string naziv) {
            eDostavaClient.eDostavaServis.GetRestoranByNazivRequest inValue = new eDostavaClient.eDostavaServis.GetRestoranByNazivRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetRestoranByNazivRequestBody();
            inValue.Body.naziv = naziv;
            eDostavaClient.eDostavaServis.GetRestoranByNazivResponse retVal = ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetRestoranByNaziv(inValue);
            return retVal.Body.GetRestoranByNazivResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoranByNazivResponse> eDostavaClient.eDostavaServis.eDostavaServisSoap.GetRestoranByNazivAsync(eDostavaClient.eDostavaServis.GetRestoranByNazivRequest request) {
            return base.Channel.GetRestoranByNazivAsync(request);
        }
        
        public System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoranByNazivResponse> GetRestoranByNazivAsync(string naziv) {
            eDostavaClient.eDostavaServis.GetRestoranByNazivRequest inValue = new eDostavaClient.eDostavaServis.GetRestoranByNazivRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetRestoranByNazivRequestBody();
            inValue.Body.naziv = naziv;
            return ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetRestoranByNazivAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eDostavaClient.eDostavaServis.GetRestoraniResponse eDostavaClient.eDostavaServis.eDostavaServisSoap.GetRestorani(eDostavaClient.eDostavaServis.GetRestoraniRequest request) {
            return base.Channel.GetRestorani(request);
        }
        
        public eDostavaClient.eDostavaServis.Restoran[] GetRestorani() {
            eDostavaClient.eDostavaServis.GetRestoraniRequest inValue = new eDostavaClient.eDostavaServis.GetRestoraniRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetRestoraniRequestBody();
            eDostavaClient.eDostavaServis.GetRestoraniResponse retVal = ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetRestorani(inValue);
            return retVal.Body.GetRestoraniResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoraniResponse> eDostavaClient.eDostavaServis.eDostavaServisSoap.GetRestoraniAsync(eDostavaClient.eDostavaServis.GetRestoraniRequest request) {
            return base.Channel.GetRestoraniAsync(request);
        }
        
        public System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetRestoraniResponse> GetRestoraniAsync() {
            eDostavaClient.eDostavaServis.GetRestoraniRequest inValue = new eDostavaClient.eDostavaServis.GetRestoraniRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetRestoraniRequestBody();
            return ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetRestoraniAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eDostavaClient.eDostavaServis.GetBlokoviResponse eDostavaClient.eDostavaServis.eDostavaServisSoap.GetBlokovi(eDostavaClient.eDostavaServis.GetBlokoviRequest request) {
            return base.Channel.GetBlokovi(request);
        }
        
        public eDostavaClient.eDostavaServis.Blok[] GetBlokovi() {
            eDostavaClient.eDostavaServis.GetBlokoviRequest inValue = new eDostavaClient.eDostavaServis.GetBlokoviRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetBlokoviRequestBody();
            eDostavaClient.eDostavaServis.GetBlokoviResponse retVal = ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetBlokovi(inValue);
            return retVal.Body.GetBlokoviResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetBlokoviResponse> eDostavaClient.eDostavaServis.eDostavaServisSoap.GetBlokoviAsync(eDostavaClient.eDostavaServis.GetBlokoviRequest request) {
            return base.Channel.GetBlokoviAsync(request);
        }
        
        public System.Threading.Tasks.Task<eDostavaClient.eDostavaServis.GetBlokoviResponse> GetBlokoviAsync() {
            eDostavaClient.eDostavaServis.GetBlokoviRequest inValue = new eDostavaClient.eDostavaServis.GetBlokoviRequest();
            inValue.Body = new eDostavaClient.eDostavaServis.GetBlokoviRequestBody();
            return ((eDostavaClient.eDostavaServis.eDostavaServisSoap)(this)).GetBlokoviAsync(inValue);
        }
    }
}
